Repository thoth-station/amun-hwinfo, pull requests merged in 2020-07, with the labels that each got.

#19 migrating to thoth application
  .coafile
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .gitignore
  .pre-commit-config.yaml
  app.py
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#20 enable the application to be maintained by bots
  .thoth.yaml
  .thothTemplate.yaml
  .zuul.yaml
  README.md
  app.py
Labels: approved, size/M

#22 Automatic update of dependency py-cpuinfo from 5.0.0 to 7.0.0
  Pipfile.lock
Labels: approved, bot, size/XS

#23 Release of version 0.1.1
  CHANGELOG.md
  app.py
Labels: approved, bot, size/S

#24 Include aicoe-ci configuration file
  .aicoe-ci.yaml
Labels: approved, size/S

#26 include platform package for amun-hwinfo
  app.py
Labels: approved, size/XS

#28 Release of version 0.1.2
  CHANGELOG.md
  app.py
Labels: approved, bot, size/XS
